# pylint: disable=[W,R,C,import-error]

class Engine:
    def evaluateFunction(self, data:dict): ...
    def saveGame(self) -> None: ...
    def loadGame(self) -> None: ...
    def getPlayer(self) -> None: ...
    def sendOutput(self) -> None: ...
    
    
    